// Generated by CoffeeScript 1.6.3
var english, messWithIt, pieceName;

pieceName = function(nom, nom1, chap, chap1, ver1, nom2, chap2, ver2) {
  var ans, them1, them2;
  them1 = ver1.split(' ');
  them2 = ver2.split(' ');
  ver1 = them1[0];
  ver2 = them2[them2.length - 1];
  if ((nom !== '' && nom !== nom1) || (chap !== chap1)) {
    if (!(ver1 === '1' && chap1 === '1')) {
      nom1 = nom;
      if (ver1 !== '1') {
        chap1 = chap;
      }
    }
  }
  ans = "" + nom1 + " " + chap1 + ":" + ver1 + (nom1 === nom2 ? (chap1 === chap2 ? (ver1 === ver2 ? '' : '-' + ver2) : '-' + chap2 + ':' + ver2) : '-' + nom2 + ' ' + chap2 + ':' + ver2);
  return ans;
};

messWithIt = function(x) {
  return english(parseInt(x));
};

english = function(x) {
  if (x < 21) {
    return ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty'][x];
  }
  if (x < 100) {
    return ['oh', 'ten-and', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety', 'hundred-and'][Math.floor(x / 10)] + ((x % 10) < 1 ? '' : '-' + english(x % 10));
  }
  if (x < 1000) {
    return english(Math.floor(x / 100)) + '-hundred and ' + english(x % 100);
  }
};

Prince.addScriptFunc('pieceName', pieceName);

Prince.addScriptFunc('messWithIt', messWithIt);
